version: '3.1'

services:
  web:
    restart: unless-stopped
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/postgres
    env_file:
      - prod.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    volumes:
      - social-data:/var/lib/postgresql/data

volumes:
  social-data:
    external: true